### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by michaelcodecany** [pablo-clueless/hardhat-nft-project#1]
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: cdg1::8xjfq-1662289632947-98d8a189adb9

**Comment by pablo-clueless** [comment]
Thanks for the heads up. I updated the URL on Vercel but forgot to change it here.

**Comment by pablo-clueless** [comment]
The issue has been fixed. the new URL is https://erc721-minter.vercel.app
